[project]
name = "16-20-crud"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.2.3",
    "sqlalchemy>=2.0.38",
    "sqlmodel>=0.0.22",
    "typing>=3.10.0.0",
]
